server:
  port: 80

#feign默认是不开启hystrix，默认值为false
feign:
  hystrix:
    enabled: true

#eureka配置
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
