server:
  port: 8002

spring:
  datasource:
    username: root
    password: mysql521695
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&useSSL=true&serverTimezone=UTC&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: springcloud-provider-dept

mybatis:
  type-aliases-package: com.msdn.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8002   # 修改eureka上的默认描述信息
    prefer-ip-address: true  # true,可以显示服务的IP地址

#info配置
info:
  app.name: hresh-springcloud
  company.name: blog.csdn.net/Herishwater
