server:
  port: 7003

#Eureka配置
eureka:
  instance:
    hostname: eureka7003 #Eureka服务端的实例名称
    prefer-ip-address: true
  client:
    register-with-eureka: false   #表示是否向注册中心注册自己
    fetch-registry: false   #为false表示自己是注册中心
    service-url:    #监控页面
      defaultZone: http://eureka7002:7002/euraka/,http://eureka7001:7001/euraka/

#spring:
#  application:
#    name: eureka-server
#  security:
#    user:
#      name: admin
#      password: admin
